name: Build

on:
  push:
    tags: ['v*']
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Rust
        run: rustup show

      - name: Setup Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: "25.3"

      - name: cargo build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          path: |
            target/x86_64-unknown-linux-musl/release/netavark-bridge-vlan-plugin
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/netavark-bridge-vlan-plugin
